# Page settings

baseurl = "/"
languageCode = "en-us"
title = "Dwai Banerjee Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = ""

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-3.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Dwai Banerjee"
        tagline = "Senior Director, Systems Architect, Full Stack Developer - Lives in The Netherlands"
        avatar = "3b27979.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: dwai@cloudgear.io"
        title = "dwai@cloudgear.io"

        #[[params.contact.list]]
        #class = "phone"
        #icon = "fa-phone"
        #url = "tel:+1234567890"
        #title = "+1234567890"

        #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//cloudgear.io"
        #title = "cloudgear.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/dbanerj"
        title = "linkedin.com/in/dbanerj"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/dwaiba"
        title = "github.com/dwaiba"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/cloudgeario"
        title = "@cloudgeario"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor of Engineering"
        college = "National Institute of Technology, India"
        dates = "1997 - 2001"

        #[[params.education.list]]
        #degree = "BSc in Applied Mathematics"
        #college = "Bristol University"
        #dates = "2007 - 2011"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native/Bilingual"

        [[params.language.list]]
        language = "Bengali"
        level = "Native/Bilingual"

        [[params.language.list]]
        language = "Hindi"
        level = "Professional"

        [[params.language.list]]
        language = "Dutch"
        level = "Elementary"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Technology"

        [[params.interests.list]]
        interest = "Reading"

        [[params.interests.list]]
        interest = "Anthropology"

        [[params.interests.list]]
        interest = "Cinema"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Solution Director"
        dates = "May, 2017 to Present"
        company = " HCL Technologies, The Netherlands and EMEA"
        details = "Public/Private Cloud enablement,Microservices on immutable infrastructures, container standards/implementations for European conglomerates. HPC/GPU compute fabrics for customers across the world."

        [[params.jobs.list]]
        position = "Cloud Solution Architect"
        dates = "January, 2016 to April, 2017"
        company = "Microsoft , The Netherlands and Seattle, United States"
        details = "Created and maintained Azure github repositories for K80 (GK210 Duo) GPU Compute Auto Linux clusters for CUDA non graphical apps. HPC Big computes RDMA/IB Auto linux clusters for Intel MPI on Azure. These are immutable, intelligent compute grids with nvdia docker options and configurable soft RAID0. Created and maintained Azure github repository for M60 Graphical 3D Apps over PCoIP with latest Windows NVIDIA Azure Skus. Maintained the Docker for Azure with OMS (Operational Management Suite) repository  with 17.0x-CE for monitoring the dockerized cloud infrastructure and first put up the automated Docker Datacenter on the Engine 1.13.x Private beta on a public cloud (Azure). Explore the repositories in the github media link with the pinned repositories @ https://github.com/dwaiba."

        [[params.jobs.list]]
        position = "Principal, Solution Architecture"
        dates = "August, 2015 to November, 2015"
        company = "Exact Software, Delft, The Netherlands"
        details = " R&D on future enabling Exact product portfolio."
        
        [[params.jobs.list]]
        position = "Senior Consultant"
        dates = "February 2013 to July, 2015"
        company = "Enable-U B.V., The Netherlands and Africa"
        details = " Governance, Integration, Security, Appliances, Registry, Cloud, API management, product dev, Nederlandse overheid (Dutch Government)."
        
        [[params.jobs.list]]
        position = "Domain Solution Architect"
        dates = "October, 2011 to January, 2013"
        company = "Canon Europa N.V., The Netherlands"
        details = "Architect for Integration and Data @ Canon Europa. Design authority for Integration, data and B2B. Designing, building, implementing and managing the Canon landscape in WebSphere, Informatica, Oracle SOA Suite, virtual Infrastructure. Establishing DevOps and automation/scaling for Middleware for platform stabilization. Building the Centre Of Excellence."
        
        [[params.jobs.list]]
        position = "Technical Architect"
        dates = "April, 2009 to October, 2011"
        company = "TMNS B.V., The Netherlands, Switzerland"
        details = "Worked on Enterprise Architecture, open systems, Oracle, WebSphere, TIBCO, Progress Sonic, Apama, Mule, JBoss, Apache projects. Consulted, designed and developed for various Dutch and Swiss businesses in the SOA, BPM and CEP space. Architected and programmed a successful CEP based Automated online Ad optimization platform. Set up large, high performing and scalable middleware infrastructure especially using VMWare, Amazon EC2 and virtualization techniques. Defined roadmaps for autonomic computing and implemented full scale AWS solutions."
        
        [[params.jobs.list]]
        position = "Technical Architect"
        dates = "June, 2007 to February, 2009"
        company = "HCL Technologies, India and across the world."
        details = "Worked primarily with Cisco AON (Application-Oriented Network), product enhancements, SaaS gateways and other solutions. CISCO AON is a network-embedded/ appliance based middleware. Led a team of developers. We developed some of the first Enterprise class SaaS device connectors. Defined end to end detailed transformation solutions and laid out numerous successful Middleware product choices / implementations for a large range of customers around the world using varied stacks from opensource ESBs, Integration appliances to Commercial SOA stacks. Built a successful SOA Governance model for the Insurance and Investments division of a large British banking conglomerate."
        
        [[params.jobs.list]]
        position = "Senior Member Technical Staff"
        dates = "April, 2006 to June, 2007"
        company = "Oracle Server Technologies, India."
        details = "Oracle’s SOA Suite 10.1.3.x and Fabric (11g) Dev team."
        
        [[params.jobs.list]]
        position = "Engineer"
        dates = "November, 2003 to April, 2006"
        company = "IBM, India and the across the world."
        details = "Worked with almost all products of the WebSphere stack, large AIX base setups, developing and consulting for various customers across the globe."
        
        [[params.jobs.list]]
        position = "Developer"
        dates = "July, 2003 to October, 2003"
        company = "Ontrack Systems Ltd., Calcutta, India"
        details = "Developer of an end to end Distributed Logistics systems for Japanese and British customers."
        
        [[params.jobs.list]]
        position = "C++/Web developer"
        dates = "2001 to July, 2003"
        company = "Various, Pan Indian sub-continent."
        details = "Worked as a java/c++/web programmer and linux administrator."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Intel Xeon Phi Coprocessors, Intel Parallel Studio XE, ITAC, Intel Lustre, GlusterFS, Mellanox 6th Generation Device Drivers, DAPL, Infiniband, RoCEv2, Intel Compilers, Intel MPI, LINPACK, IMB and various other benchmarking, MPI 2.2/3.0/3.1, NUMA, mpicc/mpiicc/icc/ifort, CUDA/CUDAnn, OFED, Open MPI, Torque (Maui/MOAB), SLURM, NVIDIA DIGITS, Toolkits like CNTK, Caffe2, Keras and Tensorflow, nvidia-docker"
        level = "90%"
                
        [[params.skills.list]]
        skill = "C/C++, Shell, Python, Go, node.js, Java EE, Spring Boot, Git, Gerrit"
        level = "90%"

        [[params.skills.list]]
        skill = "Linux, UNIX, Fedora, RHEL, CentOS, Ubuntu, Custom Kernels, AIX, HP-UX and various other flavours"
        level = "90%"

        [[params.skills.list]]
        skill = "Cloud overlays, Google Cloud, AWS, Microsoft Azure, Digital Ocean, IBM Bluemix, CloudFoundry, Full scale Templatized deployable immutable cloud solutions, CLIs and Cloud APIs, Scaling, Iaas Clusters, Various PaaS on CSPs"
        level = "90%"

        [[params.skills.list]]
        skill = "API Management , API Security, API Design, node-red, netflix spring boot, Loopback, 3scale, WS02, Open Source API Management, Keycloak, CA Layer7, IDM Stacks"
        level = "90%"

        [[params.skills.list]]
        skill = "Hypervisors, Microvisors,KVM, Hyper-V, VMWare, vagrant, Hashicorp tools"
        level = "90%"
        
        [[params.skills.list]]
        skill = "Container Management Platforms, Kubernetes/Heptio/GCE, Docker Data Center with Universal Control Plane, Swarm Mode, Rancher, rkt, oci, containerd, etcd, zookeeper, Mesosphere, docker plugins, Docker CE, Red hat Openshift, Registries, container pipelines, Jenkins, TeamCity, VSTS, Various CLIs and APIs
        level = "90%"
        
        [[params.skills.list]]
        skill = "Middleware and ESB, WebSphere Stack and topologies, WebSphere ESB, Oracle SOA Suite components, JBoss Community and EAP components, Fuse, Mule distributed, Websphere MQ, AMQP, Event Hubs, Software AG Apama Event Monitors"
        level = "90%"
        
        [[params.skills.list]]
        skill = "HTML5/CSS3, Javascript, Ruby, Erlang, Perl, SQL, Esql, Various Script frameworks like Apama Event Monitoring Scripts"
        level = "80%"
        
        [[params.skills.list]]
        skill = "DB2, Oracle RDBMS, SQL Server, Postgressql, Redis, mongodb, HBase"
        level = "80%"
                
        [[params.skills.list]]
        skill = "Hadoop Data Platform components, YARN and scheduling, HDFS, Apache Kafka, Apache Phoenix, SparkML, Data Lake Pattens, HDinsights, Livy"
        level = "70%"
               

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Dwai"
